server:
  port: ${BOARD_SERVICE_PORT:8081}

spring:
  application:
    name: board-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
